[build.environment]
NETLIFY_IMAGE_CDN = "true"

[images]
remote_images = [
  "https://cdn.uoguelph.ca/.*",
  "https://api.liveugconthub.uoguelph.dev/.*",
  "https://api.testugconthub.uoguelph.dev/.*",
  "https://.*.pantheonsite.io/.*"
]

[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "gzip"
