[build.environment]
NETLIFY_IMAGE_CDN = "true"

[images]
remote_images = [
  "https://cdn.uoguelph.ca/.*",
  "https://api.liveugconthub.uoguelph.dev/.*",
  "https://api.testugconthub.uoguelph.dev/.*",
  "https://api.devugconthub.uoguelph.dev/.*",
  "https://.*.pantheonsite.io/.*"
]

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    path = "programs/bachelor-of-mathematics"
    output_path = "reports/ba-math.html"

  [[plugins.inputs.audits]]
    path = "programs/bachelor-of-computing"
    output_path = "reports/ba-comp.html"

  [[plugins.inputs.audits]]
    path = "programs/bachelor-of-engineering"
    output_path = "reports/ba-eng.html"

  [[plugins.inputs.audits]]
    path = "programs/bachelor-of-science"
    output_path = "reports/ba-sci.html"

  [[plugins.inputs.audits]]
    path = "programs/bachelor-of-indigenous-environmental-science-and-practice/"
    output_path = "reports/ba-indigenous.html"