#!/bin/bash

# This script runs visual regression tests using BackstopJS.


# Backstop visual regression
echo -e "\nRunning backstop reference..."
backstop reference --config=.ci/test/visual-regression/backstopConfig.js --sitename=${Release.DefinitionName}

# Backstop test
echo -e "\nRunning backstop test..."
VISUAL_REGRESSION_RESULTS=$(backstop test --config=.ci/test/visual-regression/backstopConfig.js --sitename=${Release.DefinitionName} || echo 'true')

echo "${VISUAL_REGRESSION_RESULTS}"

if [[ ${VISUAL_REGRESSION_RESULTS} == *"Mismatch errors found"* ]]
then
	# visual regression failed
	echo -e "\nVisual regression test failed!"
else
	# visual regression passed
	echo -e "\n\nVisual regression test passed!"
fi

if [[ ${VISUAL_REGRESSION_RESULTS} == *"Mismatch errors found"* ]]
then
    exit 1
fi