#!/bin/bash

# Install Terminus
sudo mkdir -p /opt/terminus &&
curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar &&
sudo php installer.phar install --install-dir=/opt/terminus --bin-dir=/usr/bin

# Authenticate terminus
terminus auth:login --machine-token="$TERMINUS_TOKEN" </dev/null
ssh-keygen -N "" -f ~/.ssh/id_rsa &&
terminus ssh-key:add ~/.ssh/id_rsa.pub </dev/null

# Update test environment if GatsbySource is set to test environment
terminus env:clone-content --cc --updatedb -y -- bovey.live test </dev/null

# Remove SSH key from Pantheon
terminus ssh-key:remove `terminus ssh-key:list --format=list </dev/null | tail -1` </dev/null

# Log out of Pantheon
terminus auth:logout </dev/null